[package]
name = "ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.0"
nannou_egui = "0.5"
core = { path = "../core" }
lazy_static = "1.4.0"
clap = { version = "4.2.1", features = ["derive"] }
